
## Numpy Notes

In [2]:
import numpy as np


import matplotlib.pyplot as plt
from scipy import misc                 # Contains the image of a racoon
from PIL import Image                   #  For reading image files



C:\Users\mathe\AppData\Local\Temp\ipykernel_25904\3669424053.py:5: DeprecationWarning: scipy.misc is deprecated and will be removed in 2.0.0
  from scipy import misc                 # Contains the image of a racoon


### Accessing the dimensions

#### One dimensional array

In [18]:
one_array = np.array([1.1 , 9.2, 8.1,4.7 ])
one_array.shape         # Seeing the rows because its a 1d block so only shows one number

one_array[2]            # Access the third item like before
one_array.ndim          # Helps to see the columns

1

#### Two dimensional array( Matrix)

In [10]:
array_2d  = np.array([
                        [1, 2, 3, 9],
                        [5, 6, 7, 8]
                        ])                  # Behaves as a nested list

print(f'array_2d has {array_2d.ndim} dimensions')       # Columns
print(f'Its shape is {array_2d.shape}')                 # Rows
print(f'It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns')
print(array_2d[1,2])            # Third value in the second row
print(array_2d[0, :])           # O column and all the rows

array_2d has 2 dimensions
Its shape is (2, 4)
It has 2 rows and 4 columns
7
[1 2 3 9]


#### N dimensions
An array with n dimensions is known as a tensor.

In [12]:
array_n = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],

                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])


##### Challenge:
How many dimensions does the array below have?

What is its shape (i.e., how many elements are along each axis)?

Try to access the value 18 in the last line of code.

Try to retrieve a 1-dimensional vector with the values [97, 0, 27, 18]

Try to retrieve a (3,2) matrix with the values [[ 0, 4], [ 7, 5], [ 5, 97]]

In [26]:
# Question 1 :
print(array_n.shape)            # There are three blocks, two rows, and three columns
print(array_n.ndim)             # This gives three since its three blocks/ dimensions
print(array_n[2,1,3])             # They all work from 0 onwards when accessing - accessing the value of 18
print(array_n[2,1,:])
print(array_n[:,:,0])              # Use all dimensions, use all rows, and get the first column value

(3, 2, 4)
3
18
[97  0 27 18]
[[ 0  4]
 [ 7  5]
 [ 5 97]]


### Generating and Manipulating ndarrays

#### Challenge 1
Use ```.arange()``` to createa a vector a with values ranging from 10 to 29. You should get this:

In [29]:
# Can use the numpy.arange( start, stop, step)  to create a vector
vector  =  np.arange(10, 29,1)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]


#### Challenge 2

Use Python slicing techniques on a to:

Create an array containing only the last 3 values of a

Create a subset with only the 4th, 5th, and 6th values

Create a subset of a containing all the values except for the first 12 (i.e., [22, 23, 24, 25, 26, 27, 28, 29])

Create a subset that only contains the even numbers (i.e, every second number)

In [42]:
# Last three values of a :
vector[-3:]         # Last thee values
vector[3:6]         # Fourth , fifth and sixth values
vector[-8:]         # Last 8 values
vector[::2]         # Star, stop, step

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### Challenge 4
Reverse the order of the values in a, so that the first element comes last:
use of ```np.flip(array)```

In [45]:
reversed_vector= np.flip(vector)
print(reversed_vector)

[28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Challenge 4
Print out all the indices of the non-zero elements in this array: [6,0,9,0,0,5,0]

In [46]:
vector1 = np.array([6,0,9,0,0,5,0])