
## Numpy Notes

In [2]:
import numpy as np


import matplotlib.pyplot as plt
from scipy import misc                 # Contains the image of a racoon
from PIL import Image                   #  For reading image files



C:\Users\mathe\AppData\Local\Temp\ipykernel_25904\3669424053.py:5: DeprecationWarning: scipy.misc is deprecated and will be removed in 2.0.0
  from scipy import misc                 # Contains the image of a racoon


#### One dimensional array

In [18]:
one_array = np.array([1.1 , 9.2, 8.1,4.7 ])
one_array.shape         # Seeing the rows because its a 1d block so only shows one number

one_array[2]            # Access the third item like before
one_array.ndim          # Helps to see the columns

1

#### Two dimensional array( Matrix)

In [10]:
array_2d  = np.array([
                        [1, 2, 3, 9],
                        [5, 6, 7, 8]
                        ])                  # Behaves as a nested list

print(f'array_2d has {array_2d.ndim} dimensions')       # Columns
print(f'Its shape is {array_2d.shape}')                 # Rows
print(f'It has {array_2d.shape[0]} rows and {array_2d.shape[1]} columns')
print(array_2d[1,2])            # Third value in the second row
print(array_2d[0, :])           # O column and all the rows

array_2d has 2 dimensions
Its shape is (2, 4)
It has 2 rows and 4 columns
7
[1 2 3 9]


#### N dimensions
An array with n dimensions is known as a tensor.

In [12]:
array_n = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                         [[7, 86, 6, 98],
                          [5, 1, 0, 4]],

                          [[5, 36, 32, 48],
                           [97, 0, 27, 18]]])


##### Challenge:
How many dimensions does the array below have?

What is its shape (i.e., how many elements are along each axis)?

Try to access the value 18 in the last line of code.

Try to retrieve a 1-dimensional vector with the values [97, 0, 27, 18]

Try to retrieve a (3,2) matrix with the values [[ 0, 4], [ 7, 5], [ 5, 97]]

In [26]:
# Question 1 :
print(array_n.shape)            # There are three blocks, two rows, and three columns
print(array_n.ndim)             # This gives three since its three blocks/ dimensions
print(array_n[2,1,3])             # They all work from 0 onwards when accessing - accessing the value of 18
print(array_n[2,1,:])
print(array_n[:,:,0])              # Use all dimensions, use all rows, and get the first column value

(3, 2, 4)
3
18
[97  0 27 18]
[[ 0  4]
 [ 7  5]
 [ 5 97]]
